name: Static analysis PHP

on:
   push:
      branches-ignore:
         - '**-dev'
   pull_request:

jobs:

  phpstan:
    runs-on: ubuntu-latest
    name: phpstan

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: gd,intl,mbstring,sqlite,zip
          coverage: disable

      - run: composer global config allow-plugins.phpstan/extension-installer true

      - run: composer global require phpstan/phpstan phpstan/extension-installer phpstan/phpstan-deprecation-rules phpstan/phpstan-strict-rules phpstan/phpstan-phpunit

      - run: composer install --no-progress --no-suggest --ignore-platform-reqs

      - run: ~/.composer/vendor/bin/phpstan analyze --no-progress --error-format=github
